/*
  Automation:  Discount-Pool-Replenishment
  Purpose:     Ensure ShopStyle_DiscountCodePool always has a buffer of >= 5,000 unused codes per
               CampaignType. Codes themselves are generated by the commerce/promotions platform and
               land in a staging DE (Staging_DiscountCodeImport) via nightly File Transfer import
               (see automation-studio/file-transfer/import-discount-codes.json); this activity
               promotes staged codes into the live pool, skipping duplicates.
  Schedule:    Daily 03:00 America/New_York.
*/

INSERT INTO ShopStyle_DiscountCodePool (DiscountCode, CampaignType, DiscountPercent, IsUsed, ExpirationDate)
SELECT
    stg.DiscountCode,
    stg.CampaignType,
    stg.DiscountPercent,
    0,
    DATEADD(day, 90, GETDATE())
FROM Staging_DiscountCodeImport AS stg
LEFT JOIN ShopStyle_DiscountCodePool AS pool ON pool.DiscountCode = stg.DiscountCode
WHERE pool.DiscountCode IS NULL;

-- Purge expired, unused codes so they don't get allocated after the promotion window closes
DELETE FROM ShopStyle_DiscountCodePool
WHERE IsUsed = 0
  AND ExpirationDate < GETDATE();
